# Generated by Django 3.2 on 2023-02-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
