# Generated by Django 3.2 on 2023-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery_threshold', models.PositiveSmallIntegerField(default=0)),
                ('slider_img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider_img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider_img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('caption1', models.CharField(max_length=254)),
                ('caption2', models.CharField(max_length=254)),
                ('caption3', models.CharField(max_length=254)),
            ],
        ),
    ]
