# Generated by Django 3.2 on 2023-02-27 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='approved',
        ),
    ]
