# Generated by Django 3.2 on 2023-02-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_deals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
